Calendar/urls.py
from django.urls import path
from . import views

app_name = 'calendar'
urlpatterns = [

    path('list/', views.CalendarListView.as_view(), name='list'),
    path('update/<int:pk>', views.CalendarUpdateView.as_view(), name='update'),
    path('detail/<int:pk>', views.CalendarDetailView.as_view(), name='detail'),

]

Profile/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'profile'
urlpatterns = [

    path('create/', views.CreatUserView.as_view(), name='create_user'),
    path('list/', views.ProfileListView.as_view(), name='list'),

    path('group/list/', views.GroupListView.as_view(), name='group_list'),
    path('group/detail/<int:pk>', views.GroupDetailView.as_view(), name='group_detail'),
    path('group/create/', views.GroupCreateView.as_view(), name='group_create'),

]

api/v1/urls.py
from django.urls import path
from .profile.views import CreateProfileApiView, CreateGroupApiView
from .lessons.views import LessonInfoCreateApiView, LessonCreateApiView, LessonsCalendarListApiView, \
    LessonDeleteApiView, LessonCalendarStudentListApiView, TimeListApiView, TimeUpdateView
app_name = 'api_v1'
urlpatterns = [
    path('lesson/time/list/', TimeListApiView.as_view(), name='lesson_time_list'),
    path('lesson/time/<int:id>', TimeUpdateView.as_view(), name='lesson_time'),
    path('profile/create/', CreateProfileApiView.as_view(), name='create_profile'),
    path('lesson/info/create/', LessonInfoCreateApiView.as_view(), name='create_lesson_info'),
    path('lesson/create/', LessonCreateApiView.as_view(), name='create_lesson'),
    path('lesson/delete/<int:id>', LessonDeleteApiView.as_view(), name='delete_lesson'),
    path('group/create/', CreateGroupApiView.as_view(), name='create_group'),
    path('lesson/calendar/list/<int:id>', LessonsCalendarListApiView.as_view(), name='lesson_list_calendar'),
    path('lesson/calendar/teacher/list/<int:id>', LessonCalendarStudentListApiView.as_view(), name='lesson_teacher_list_calendar'),
    path('lesson/calendar/student/list/<int:id>', LessonsCalendarListApiView.as_view(), name='lesson_list_calendar'),
]

urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Index.urls')),
    path('lesson/', include('Lesson.urls')),
    path('profile/', include('Profile.urls')),
    path('calendar/', include('Calendar.urls')),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('api/v1/', include('api.v1.urls')),
]

Calendar/models.py
from django.db import models

# Create your models here.

Profile/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    LEVEL = (
        ("Teacher", "Преподаватель"),
        ("Student", "Студент"),
        ("Training_division", "Учебный отдел")
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, null=True)
    last_name = models.CharField(max_length=255, null=True)
    otchestvo = models.CharField(max_length=255, null=True)
    level = models.CharField(max_length=255, choices=LEVEL)

    def __str__(self):
        return self.user.username


class StudentGroup(models.Model):
    students = models.ManyToManyField(Profile, limit_choices_to={'level': "Student"})
    group_name = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.group_name

Calendar/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views import generic

from Lesson.models import LessonInfo, LessonTime
from Profile.models import StudentGroup




class CalendarListView(LoginRequiredMixin, generic.ListView):
    template_name = 'calendar/list.html'
    model = StudentGroup
    def get_queryset(self):
        if self.request.user.profile.level == "Training_division":
            return StudentGroup.objects.all()
        elif self.request.user.profile.level == "Teacher":
            return StudentGroup.objects.filter(lesson__lesson_info__teacher=self.request.user.profile).distinct().all()
        elif self.request.user.profile.level == "Student":
            return self.request.user.profile.studentgroup_set.all()
        return StudentGroup.objects.none()


class CalendarUpdateView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'calendar/update/calendar.html'
    model = StudentGroup

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["lesson_info_list"] = LessonInfo.objects.all()
        context["lesson_time_list"] = LessonTime.objects.all()
        return context


class CalendarDetailView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'calendar/detail.html'
    model = StudentGroup

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["lesson_info_list"] = LessonInfo.objects.all()
        context["lesson_time_list"] = LessonTime.objects.all()
        return context

templates/calendar/calendar_detail.html
{% extends 'base.html' %}

{% load static %}




{% block content %}


    <div class="row">
        <div class="col-md-12">
            <div id='calendar'></div>

        </div>
    </div>

    <script>

        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            var url = "{% url 'api_v1:lesson_list_calendar' studentgroup.id %}";
            var curday;
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                selectable: true,
                locale: 'ru',
                {#slotLabelInterval: "01:30:00",#}
                dateClick: function (info) {

                    $.getJSON(url, {day: info.dateStr}, function (data, textStatus, jqXHR) {
                        for (key in data) {
                            $('#' + data[key].less_numb).val(data[key].less_info_id);
                        }
                        curday = data;
                    });
                    selected_date = info.dateStr
                    dialog.dialog("open");

                    // change the day's background color just for fun
                    // info.dayEl.style.backgroundColor = 'red';
                },
                eventSources: [

                    // your event source
                    {
                        url: url,
                        method: 'GET',
                        failure: function () {
                            alert(url);
                        },
                        color: 'yellow',   // a non-ajax option
                        textColor: 'black' // a non-ajax option
                    }

                    // any other sources...

                ]

            });


            calendar.render();

            var dialog, form, selected_date;


            function addUser() {

                lessons_form = document.getElementById("lessons_form").elements;
                for (i = 1; i < lessons_form.length; i++) {

                    let formData = new FormData();

                    if (lessons_form[i].value === "") {
                        for (key in curday) {
                            if (curday[key].less_numb === lessons_form[i].id) {
                                var delete_url = "/api/v1/lesson/delete/" + curday[key].id;
                                $.ajax({
                                    headers: {"X-CSRFToken": "{{csrf_token}}"},
                                    url: delete_url,
                                    processData: false,
                                    contentType: false,
                                    method: 'DELETE',
                                    success: function (data) {
                                        {#alert('успех! 22');#}
                                    },
                                    error: function (data) {
                                        {#alert('Ошибка 22');#}
                                    }
                                });
                            }
                        }

                    }
                    if (lessons_form[i].value !== "") {
                        formData.append('lesson_info', lessons_form[i].value);
                        formData.append('day', selected_date);
                        formData.append('lesson_time', lessons_form[i].id);
                        formData.append('group', "{{studentgroup.id}}");
                        var url = "{% url 'api_v1:create_lesson' %}";
                        $.ajax({
                            headers: {"X-CSRFToken": "{{csrf_token}}"},
                            url: url,
                            processData: false,
                            contentType: false,
                            method: 'POST',
                            data: formData,
                            success: function (data) {

                                {#alert('успех!');#}
                            },
                            error: function (data) {
                                {#alert('Ошибка');#}
                            }
                        });
                    }
                }

                {#calendar.fullCalendar('refetch');#}
                location.reload();
            }

            dialog = $("#dialog-form").dialog({
                autoOpen: false,
                height: 460,
                width: 350,
                modal: true,
                buttons: {
                    "применить": addUser,
                    Cancel: function () {
                        dialog.dialog("close");
                    }
                },
                close: function () {
                    form[0].reset();
                }
            });

            form = dialog.find("form").on("submit", function (event) {
                event.preventDefault();
                addUser();
            });


        });


    </script>
    <script>

    </script>

    <div id="dialog-form" title="Расписание">
        <form id="lessons_form">
            <fieldset>
                {% for lesson_time in lesson_time_list %}
                    <div class="form-group">
                        <label for="{{ lesson_time.number }}">{{ lesson_time.number }} Пара </label>
                        <select class="form-control" id="{{ lesson_time.number }}">
                            <option id="" value=""></option>
                            {% for lesson_info in lesson_info_list %}
                                <option value="{{ lesson_info.id }}">{{ lesson_info.name }}</option>
                            {% endfor %}

                        </select>
                    </div>
                {% endfor %}


            </fieldset>
        </form>

    </div>
{% endblock %}

templates/calendar/calendar_list.html
{% extends 'base.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="right-div">
                <a class="btn btn-success" href="{% url 'profile:group_create' %}"> <i class="fa fa-plus "></i>Добавить</a>
            </div>
        </div>
        <div class="col-md-12">
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    Группы
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="lesson_info_table">

                            <thead>

                            <tr>
                                <th class="text-center">№</th>
                                <th class="text-center">Группа</th>
                                <th class="text-center">Кол-во</th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for group in studentgroup_list %}
                                <tr class="odd gradeX">

                                        <td>{{ forloop.counter }}</td>
                                    <td><a href="{% url 'calendar:calendar_detail' group.id %}">{{ group.group_name }}</a></td>
                                        <td>{{ group.students.count }}</td>

                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>
                    </div>

                </div>
            </div>
            <!--End Advanced Tables -->
        </div>
    </div>

{% endblock %}

templates/calendar/detail.html
{% extends 'base.html' %}

{% load static %}




{% block content %}


    <div class="row">
        <div class="col-md-12">
            <div id='calendar'></div>

        </div>
    </div>

    <script>

        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            var url = "{% url 'api_v1:lesson_list_calendar' studentgroup.id %}";
            var curday;
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                selectable: true,
                locale: 'ru',
                eventSources: [
                    {
                        url: url,
                        method: 'GET',
                        failure: function () {
                            alert(url);
                        },
                        {#color: 'yellow',#}
                        {#textColor: 'black'#}
                    }


                ],
                eventTimeFormat: { // like '14:30:00'
                    hour: '2-digit',
                    minute: '2-digit',
                    meridiem: false
                }

            });

            calendar.render();

        });


    </script>


{% endblock %}

templates/calendar/list.html
{% extends 'base.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-12">
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    Группы
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="lesson_info_table">

                            <thead>

                            <tr>
                                <th class="text-center">№</th>
                                <th class="text-center">Группа</th>
                                <th class="text-center">Кол-во</th>
                                {% if request.user.profile.level == "Training_division" %}
                                <th class="text-center" style="width: 20px;">Обновить</th>
                                {% endif %}

                            </tr>
                            </thead>
                            <tbody>
                            {% for group in studentgroup_list %}
                                <tr class="odd gradeX">

                                    <td class="text-center">{{ forloop.counter }}</td>
                                    <td class="text-center"><a href="{% url 'calendar:detail' group.id %}">{{ group.group_name }}</a></td>
                                    <td class="text-center">{{ group.students.count }}</td>
                                    {% if request.user.profile.level == "Training_division" %}
                                    <td class="text-center" style="width: 20px;"><a class="btn btn-primary btn-sm" style="" href="{% url 'calendar:update' group.id %}"> <i
                                                class="fa fa-refresh "></i></a></td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>
                    </div>

                </div>
            </div>
            <!--End Advanced Tables -->
        </div>
    </div>

{% endblock %}

templates/calendar/teacher_calendar.html
{% extends 'base.html' %}

{% load static %}




{% block content %}


    <div class="row">
        <div class="col-md-12">
            <div id='calendar'></div>

        </div>
    </div>

    <script>

        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            var url = "{% url 'api_v1:lesson_teacher_list_calendar' request.user.profile.id %}";
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                selectable: true,
                locale: 'ru',
                eventSources: [

                    // your event source
                    {
                        url: url,
                        method: 'GET',
                        failure: function () {
                            alert(url);
                        },
                        color: 'yellow',   // a non-ajax option
                        textColor: 'black' // a non-ajax option
                    }

                    // any other sources...
                ]
            });


            calendar.render();




        });


    </script>


{% endblock %}