Lesson/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'lesson'
urlpatterns = [

    path('time/list/', views.LessonsTimeView.as_view(), name='time'),
    path('time/update/', views.LessonsTimeUpdateView.as_view(), name='time_update'),
    path('info/list/', views.LessonInfoListView.as_view(), name='info'),
    path('info/create/', views.LessonInfoCreateVirew.as_view(), name='lesson_info_create'),


]

urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Index.urls')),
    path('lesson/', include('Lesson.urls')),
    path('profile/', include('Profile.urls')),
    path('calendar/', include('Calendar.urls')),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('api/v1/', include('api.v1.urls')),
]

Lesson/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

# Create your models here.
from Profile.models import StudentGroup, Profile


class TeacherInfo(models.Model):
    user = models.OneToOneField(Profile, on_delete=models.CASCADE)
    subject = models.CharField(max_length=255)
    position = models.CharField(max_length=255)


class LessonType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class LessonTime(models.Model):
    number = models.IntegerField(validators=[MaxValueValidator(10), MinValueValidator(1)], unique=True)
    start = models.TimeField()
    end = models.TimeField()


    def __str__(self):
        return "%s %s " % (self.number, "пара")


class LessonInfo(models.Model):
    name = models.CharField(max_length=255)
    type = models.ForeignKey(LessonType, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Profile, on_delete=models.CASCADE, limit_choices_to={'level': "Teacher"})

    def __str__(self):
        return self.name


class Lesson(models.Model):
    day = models.DateField()
    lesson_info = models.ForeignKey(LessonInfo, on_delete=models.CASCADE)
    zoom_join_url = models.URLField(null=True, blank=True)
    group = models.ForeignKey(StudentGroup, on_delete=models.CASCADE, null=True)
    lesson_time = models.ForeignKey(LessonTime, on_delete=models.CASCADE)
    zoom_start_url = models.URLField(null=True, blank=True)
    zoom_id = models.CharField(null=True, max_length=255)


    def get_start_datetime(self):
        return str(self.day) + "T" + str(self.lesson_time.start)

    def get_end_datetime(self):
        return str(self.day) + "T" + str(self.lesson_time.end)

    def get_less_name(self):
        return self.lesson_info.name

    def get_join_url(self):
        return self.zoom_join_url

    def get_start_url(self):
        return self.zoom_start_url

    def get_less_time_number(self):
        return self.lesson_time.number

    def get_les_info_id(self):
        return self.lesson_info.id

Lesson/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import generic
# Create your views here.
from Lesson.models import LessonTime, LessonInfo, LessonType, Lesson
from Profile.models import Profile
import datetime


class LessonsTimeView(generic.ListView):
    template_name = 'lesson/time.html'
    model = LessonTime
    ordering = "number"


class LessonsTimeUpdateView(LoginRequiredMixin, generic.ListView):
    template_name = 'lesson/update/time.html'
    model = LessonTime
    ordering = "number"


class LessonInfoListView(LoginRequiredMixin, generic.ListView):
    template_name = 'lesson/list.html'
    model = LessonInfo

    def get_queryset(self):
        if self.request.user.profile.level == "Training_division":
            return LessonInfo.objects.all()
        elif self.request.user.profile.level == "Teacher":
            return LessonInfo.objects.filter(teacher_id=self.request.user.profile.id)
        elif self.request.user.profile.level == "Student":
            return LessonInfo.objects.filter(lesson__group__in=self.request.user.profile.studentgroup_set.all())
        return LessonInfo.objects.none()


class LessonInfoCreateVirew(LoginRequiredMixin, generic.TemplateView):
    template_name = 'lesson/create/info.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["teacher_list"] = Profile.objects.filter(level="Teacher")
        context["type_list"] = LessonType.objects.all()
        return context

api/v1/lessons/views.py
import datetime

from django.db.models import Q
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from Lesson.models import LessonInfo, Lesson, LessonTime
from .serializers import LessonInfoCreateSerializer, LessonCreateSerializer, LessonInfoSerializer, \
    LessonDeleteSerializer, LessonsTimeSerializer, LessonsUpdateSerializer, LessonInfoTeacherSerializer


class LessonInfoCreateApiView(generics.CreateAPIView):
    queryset = LessonInfo.objects.all()
    serializer_class = LessonInfoCreateSerializer

    def post(self, request, *args, **kwargs):
        if request.user.profile.level != "Training_division":
            return Response({'error': 'you not have permission '}, status=401)
        return super(LessonInfoCreateApiView, self).post(request, *args, **kwargs)


class LessonCreateApiView(generics.CreateAPIView):
    queryset = Lesson.objects.all()
    serializer_class = LessonCreateSerializer

    def post(self, request, *args, **kwargs):
        if request.user.profile.level != "Training_division":
            return Response({'errorLessonInfoSerializer': 'you not have permission '}, status=401)
        return super(LessonCreateApiView, self).post(request, *args, **kwargs)


class LessonDeleteApiView(generics.DestroyAPIView):
    queryset = Lesson.objects.all()
    lookup_url_kwarg = "id"
    serializer_class = LessonDeleteSerializer

    def delete(self, request, *args, **kwargs):
        if request.user.profile.level != "Training_division":
            return Response({'error': 'you not have permission '}, status=401)
        return super().delete(request, *args, **kwargs)


class LessonsCalendarListApiView(generics.ListAPIView):
    def get_serializer_class(self):
        if self.request.user.profile.level == "Teacher":
            return LessonInfoTeacherSerializer
        return LessonInfoSerializer

    def get_queryset(self):
        if self.request.GET.get("day"):
            return Lesson.objects.filter(group=self.kwargs["id"], day=self.request.GET.get("day"))
        if self.request.user.profile.level == "Teacher":
            Lesson.objects.filter(group=self.kwargs["id"], lesson_info__teacher=self.request.user.profile)
        return Lesson.objects.filter(group=self.kwargs["id"])



class LessonCalendarStudentListApiView(generics.ListAPIView):
    serializer_class = LessonInfoSerializer

    def get_queryset(self):
        return Lesson.objects.filter(lesson_info__teacher_id=self.kwargs["id"])

class TimeListApiView(generics.ListAPIView):
    queryset = LessonTime.objects.all()
    serializer_class = LessonsTimeSerializer


class TimeUpdateView(generics.UpdateAPIView, generics.RetrieveAPIView):
    permission_classes = [IsAuthenticated]
    queryset = LessonTime.objects.all()
    serializer_class = LessonsUpdateSerializer
    lookup_url_kwarg = 'id'

    def get_permissions(self):
        if self.request.method == 'GET':
            return []
        return super(TimeUpdateView, self).get_permissions()

    def put(self, request, *args, **kwargs):
        if request.user.profile.level != "Training_division":
            return Response({'error': 'you not have permission '}, status=401)
        return super(TimeUpdateView, self).put(request, *args, **kwargs)

templates/lesson/list.html
{% extends "base.html" %}

{% block content %}
    {% if request.user.profile.level == "Training_division" %}
    <div class="row">
        <div class="col-md-12">

            <div class="right-div">
                <a class="btn btn-success" href="{% url 'lesson:lesson_info_create' %}"> <i class="fa fa-plus "></i>Добавить</a>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-md-12">
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    Дисциплины
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="lesson_info_table">

                            <thead>

                            <tr>
                                <th class="text-center">№</th>
                                <th class="text-center">Дисциплина</th>
                                <th class="text-center">ФИО Преподавателя</th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for lesson in lessoninfo_list %}
                                <tr class="odd gradeX">
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ lesson.name }}({{ lesson.type }})</td>
                                    <td>{% if  lesson.teacher.last_name %}{{ lesson.teacher.last_name }}{% endif %} {% if  lesson.teacher.first_name %}{{ lesson.teacher.first_name }}{% endif %} {% if  lesson.teacher.otchestvo %}{{ lesson.teacher.otchestvo }}{% endif %}</td>

                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>
                    </div>

                </div>
            </div>
            <!--End Advanced Tables -->
        </div>

    </div>
    </div>




{% endblock %}

templates/lesson/time.html
{% extends 'base.html' %}

{% block content %}
    <style>
        th, td {
            text-align: center;
        }
    </style>


    {% if request.user.profile.level == "Training_division" %}
        <div class="row">
            <div class="col-md-12">
                <div class="right-div">
                    <a class="btn btn-primary" href="{% url 'lesson:time_update' %}"> <i class="fa fa-edit "></i>
                        Редактировать </a>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-12">

            <!--   Kitchen Sink -->
            <div class="panel panel-default">
                <div class="panel-heading text-center">
                    Время занятий
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>Пара</th>
                                <th>Начало</th>
                                <th>Конец</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for time in lessontime_list %}
                                <tr>

                                    <td>{{ time.number }}</td>
                                    <td>{{ time.start.isoformat }}</td>
                                    <td>{{ time.end.isoformat }}</td>

                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- End  Kitchen Sink -->
        </div>
    </div>
{% endblock %}