Calendar/urls.py
from django.urls import path
from . import views

app_name = 'calendar'
urlpatterns = [

    path('list/', views.CalendarListView.as_view(), name='list'),
    path('update/<int:pk>', views.CalendarUpdateView.as_view(), name='update'),
    path('detail/<int:pk>', views.CalendarDetailView.as_view(), name='detail'),

]

Index/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'Index'
urlpatterns = [
    path('', views.IndexView.as_view(), name='Index'),
]

Lesson/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'lesson'
urlpatterns = [

    path('time/list/', views.LessonsTimeView.as_view(), name='time'),
    path('time/update/', views.LessonsTimeUpdateView.as_view(), name='time_update'),
    path('info/list/', views.LessonInfoListView.as_view(), name='info'),
    path('info/create/', views.LessonInfoCreateVirew.as_view(), name='lesson_info_create'),


]

Profile/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'profile'
urlpatterns = [

    path('create/', views.CreatUserView.as_view(), name='create_user'),
    path('list/', views.ProfileListView.as_view(), name='list'),

    path('group/list/', views.GroupListView.as_view(), name='group_list'),
    path('group/detail/<int:pk>', views.GroupDetailView.as_view(), name='group_detail'),
    path('group/create/', views.GroupCreateView.as_view(), name='group_create'),

]

api/v1/urls.py
from django.urls import path
from .profile.views import CreateProfileApiView, CreateGroupApiView
from .lessons.views import LessonInfoCreateApiView, LessonCreateApiView, LessonsCalendarListApiView, \
    LessonDeleteApiView, LessonCalendarStudentListApiView, TimeListApiView, TimeUpdateView
app_name = 'api_v1'
urlpatterns = [
    path('lesson/time/list/', TimeListApiView.as_view(), name='lesson_time_list'),
    path('lesson/time/<int:id>', TimeUpdateView.as_view(), name='lesson_time'),
    path('profile/create/', CreateProfileApiView.as_view(), name='create_profile'),
    path('lesson/info/create/', LessonInfoCreateApiView.as_view(), name='create_lesson_info'),
    path('lesson/create/', LessonCreateApiView.as_view(), name='create_lesson'),
    path('lesson/delete/<int:id>', LessonDeleteApiView.as_view(), name='delete_lesson'),
    path('group/create/', CreateGroupApiView.as_view(), name='create_group'),
    path('lesson/calendar/list/<int:id>', LessonsCalendarListApiView.as_view(), name='lesson_list_calendar'),
    path('lesson/calendar/teacher/list/<int:id>', LessonCalendarStudentListApiView.as_view(), name='lesson_teacher_list_calendar'),
    path('lesson/calendar/student/list/<int:id>', LessonsCalendarListApiView.as_view(), name='lesson_list_calendar'),
]

urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Index.urls')),
    path('lesson/', include('Lesson.urls')),
    path('profile/', include('Profile.urls')),
    path('calendar/', include('Calendar.urls')),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('api/v1/', include('api.v1.urls')),
]

Profile/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    LEVEL = (
        ("Teacher", "Преподаватель"),
        ("Student", "Студент"),
        ("Training_division", "Учебный отдел")
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, null=True)
    last_name = models.CharField(max_length=255, null=True)
    otchestvo = models.CharField(max_length=255, null=True)
    level = models.CharField(max_length=255, choices=LEVEL)

    def __str__(self):
        return self.user.username


class StudentGroup(models.Model):
    students = models.ManyToManyField(Profile, limit_choices_to={'level': "Student"})
    group_name = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.group_name

Profile/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from Profile.models import StudentGroup, Profile


class GroupListView(LoginRequiredMixin, generic.ListView):
    template_name = 'profile/group/list.html'
    model = StudentGroup


class GroupCreateView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'profile/create/group.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["student_list"] = Profile.objects.filter(level="Student")
        return context


class CreatUserView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'profile/create/profile.html'


class ProfileListView(LoginRequiredMixin, generic.ListView):
    model = Profile
    template_name = 'profile/list.html'


class GroupDetailView(LoginRequiredMixin, generic.DetailView):
    model = StudentGroup
    template_name = 'profile/group/detail.html'

api/v1/profile/views.py
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from Profile.models import Profile
from .serializers import ProfileSerializer, CreateGroupSerializer


class CreateProfileApiView(generics.CreateAPIView):
    permission_classes = [IsAuthenticated]
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer

    def post(self, request, *args, **kwargs):
        if request.user.profile.level != "Training_division":
            return Response({'error': 'you not have permission '}, status=401)
        return super(CreateProfileApiView, self).post(request, *args, **kwargs)

class CreateGroupApiView(generics.CreateAPIView):
    serializer_class = CreateGroupSerializer

    def post(self, request, *args, **kwargs):
        if request.user.profile.level != "Training_division":
            return Response({'error': 'you not have permission '}, status=401)
        return super(CreateGroupApiView, self).post(request, *args, **kwargs)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'/>
    <!-- Calendar  -->
    <link href='{% static 'js/fullcalendar-5.3.2/lib/main.css' %}' rel='stylesheet'/>
    <script src='{% static 'js/fullcalendar-5.3.2/lib/main.js' %}'></script>

    <!-- jquery-ui  -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <title>zoom edu</title>
    <!-- BOOTSTRAP CORE STYLE  -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet"/>
    <!-- FONT AWESOME STYLE  -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet"/>
    <!-- CUSTOM STYLE  -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    <!-- GOOGLE FONT -->
    <link href="{% static 'js/dataTables/dataTables.bootstrap.css' %}" rel="stylesheet"/>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'/>
    {#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
</head>
<body>
<div class="navbar navbar-inverse set-radius-zero">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>


        </div>
        <div class="row">


            <div class="pull-right right-div">
                <h4> username: {{ request.user.username }} </h4>
                <a href="{% url 'logout' %}" class="btn btn-danger">Выход</a>
            </div>

        </div>


    </div>
</div>
<!-- LOGO HEADER END-->
<section class="menu-section">

    <div class="container">
        <div class="row ">
            <div class="col-md-12">
                <div class="navbar-collapse collapse ">
                    <ul id="menu-top" class="nav navbar-nav navbar-left">
                        <li><a id="nav-stream" href="/" class="">Главная</a></li>
                    </ul>
                    <ul id="menu-top" class="nav navbar-nav navbar-right">

                        <li><a id="nav-stream" href="{% url "calendar:list" %}" class="">Расписание</a></li>
                        <li><a id="nav-subs" href="{% url "lesson:time" %}">Время занятий</a></li>
                        {% if request.user.profile.level == "Training_division" %}
                            <li><a id="nav-mystreams" href="{% url "profile:list" %}">пользователи</a></li>
                        {% endif %}
                        <li><a id="nav-create" href="{% url 'lesson:info' %}">Дисциплины</a></li>

                        {% if request.user.profile.level == "Student" %}
                            <li><a id="nav-create" href="{% url 'profile:group_list' %}">Моя группа</a></li>
                        {% else %}
                            <li><a id="nav-create" href="{% url 'profile:group_list' %}">Группы</a></li>
                        {% endif %}


                    </ul>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- MENU SECTION END-->
<div class="content-wrapper">
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</div>
<!-- CONTENT-WRAPPER SECTION END-->
<section class="footer-section">
    <div class="container">
        <div class="row">


        </div>
    </div>
</section>
{#    <!-- CORE JQUERY  -->#}
{#    <script src="{% static "js/jquery-1.10.2.js" %}"></script>#}
{#    <!-- BOOTSTRAP SCRIPTS  -->#}
<script src="{% static "js/bootstrap.js" %}"></script>
{#    <!-- DATATABLE SCRIPTS  -->#}
<script src="{% static "js/dataTables/jquery.dataTables.js" %}"></script>
<script src="{% static "js/dataTables/dataTables.bootstrap.js" %}"></script>
{#      <!-- CUSTOM SCRIPTS  -->#}
<script src="{% static "js/custom.js" %}"></script>

</body>
</html>

templates/calendar_detail.html
{% extends 'base.html' %}

{% load static %}




{% block content %}


    <div class="row">
        <div class="col-md-12">
            <div id='calendar'></div>

        </div>
    </div>

    <script>

        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            var url = "{% url 'api_v1:lesson_list_calendar' studentgroup.id %}";
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                selectable: true,
                locale: 'ru',
                dateClick: function (info) {
                    {#alert('Clicked on: ' + info.dateStr);#}

                    $.getJSON(url, {day: info.dateStr}, function (data, textStatus, jqXHR) {
                        {#alert('status: ' + textStatus + ', data:' + data[0].start);#}
                        for (key in data) {
                            $('#' + data[key].less_numb).val(data[key].less_info_id);
                            $('#delete_les_' + data[key].less_numb).val(data[key].id);
                        }
                    });
                    selected_date = info.dateStr
                    dialog.dialog("open");

                    // change the day's background color just for fun
                    // info.dayEl.style.backgroundColor = 'red';
                },
                eventSources: [

                    // your event source
                    {
                        url: url,
                        method: 'GET',
                        failure: function () {
                            alert(url);
                        },
                        color: 'yellow',   // a non-ajax option
                        textColor: 'black' // a non-ajax option
                    }

                    // any other sources...

                ]

            });


            calendar.render();

            var dialog, form, selected_date;


            function addUser() {

                lessons_form = document.getElementById("lessons_form").elements;
                for (i = 1; i < lessons_form.length; i++) {

                    let formData = new FormData();

                    if (document.getElementById("delete_les_" + lessons_form[i].id).value !== "") {
                        var delete_url = "/api/v1/lessons/delete/" + document.getElementById("delete_les_" + lessons_form[i].id).value
                        $.ajax({
                            headers: {"X-CSRFToken": "{{csrf_token}}"},
                            url: delete_url,
                            processData: false,
                            contentType: false,
                            method: 'DELETE',
                            success: function (data) {
                                {#alert('успех! 22');#}
                            },
                            error: function (data) {
                                {#alert('Ошибка 22');#}
                            }
                        });
                    }
                    if (lessons_form[i].value !== "") {
                        formData.append('lesson_info', lessons_form[i].value);
                        formData.append('day', selected_date);
                        formData.append('lesson_time', lessons_form[i].id);
                        formData.append('group', "{{studentgroup.id}}");
                        var url = "{% url 'api_v1:create_lesson' %}";
                        $.ajax({
                            headers: {"X-CSRFToken": "{{csrf_token}}"},
                            url: url,
                            processData: false,
                            contentType: false,
                            method: 'POST',
                            data: formData,
                            success: function (data) {

                                {#alert('успех!');#}
                            },
                            error: function (data) {
                                {#alert('Ошибка');#}
                            }
                        });
                    }
                }

                {#calendar.fullCalendar('refetch');#}
                location.reload();
            }

            dialog = $("#dialog-form").dialog({
                autoOpen: false,
                height: 460,
                width: 350,
                modal: true,
                buttons: {
                    "применить": addUser,
                    Cancel: function () {
                        dialog.dialog("close");
                    }
                },
                close: function () {
                    form[0].reset();
                }
            });

            form = dialog.find("form").on("submit", function (event) {
                event.preventDefault();
                addUser();
            });


        });


    </script>
    <script>

    </script>

    <div id="dialog-form" title="Расписание">
        <form id="lessons_form">
            <fieldset>
                {% for lesson_time in lesson_time_list %}
                    <div class="form-group">
                        <label for="{{ lesson_time.number }}">{{ lesson_time.number }} Пара </label>
                        <select class="form-control" id="{{ lesson_time.number }}">
                            <option id="delete_les_{{ lesson_time.number }}" value=""></option>
                            {% for lesson_info in lesson_info_list %}
                                <option value="{{ lesson_info.id }}">{{ lesson_info.name }}</option>
                            {% endfor %}

                        </select>
                    </div>
                {% endfor %}


            </fieldset>
        </form>

    </div>
{% endblock %}

templates/calendar_list.html
{% extends 'base.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="right-div">
                <a class="btn btn-success" href="{% url 'Index:group_create' %}"> <i class="fa fa-plus "></i>Добавить</a>
            </div>
        </div>
        <div class="col-md-12">
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    Группы
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="lesson_info_table">

                            <thead>

                            <tr>
                                <th class="text-center">№</th>
                                <th class="text-center">Группа</th>
                                <th class="text-center">Кол-во</th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for group in studentgroup_list %}
                                <tr class="odd gradeX">

                                        <td>{{ forloop.counter }}</td>
                                    <td><a href="{% url 'Index:calendar_detail' group.id %}">{{ group.group_name }}</a></td>
                                        <td>{{ group.students.count }}</td>

                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>
                    </div>

                </div>
            </div>
            <!--End Advanced Tables -->
        </div>
    </div>

{% endblock %}

templates/crate_user.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading text-center">
                    Добавить пользователя
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label>Фамилия</label>
                        <input id="last_name" class="form-control" type="text" value=""/>
                    </div>
                    <div class="form-group">
                        <label>Имя</label>
                        <input id="first_name" class="form-control" type="text" value=""/>
                    </div>
                    <div class="form-group">
                        <label>Отчество</label>
                        <input id="otchestvo" class="form-control" type="text" value=""/>
                    </div>
                    <div class="form-group">
                        <label>Логин</label>
                        <input id="username" class="form-control" type="text" value=""/>
                    </div>
                    <div class="form-group">
                        <label>Пароль</label>
                        <input id="password" class="form-control" type="password" value=""/>
                    </div>
                    <div class="form-group">
                        <label for="level">Роль</label>
                        <select class="form-control" id="level" name="level">
                            <option value="Teacher">Преподаватель</option>
                            <option value="Student">Студент</option>
                            <option value="Training_division">Учебный отдел</option>
                        </select>
                    </div>
                    <button id="create_btn" class="btn btn-info" onclick="create_user()" data-url="{% url 'api_v1:create_profile' %}">Добавить</button>
                </div>
            </div>
        </div>
    </div>

    <script>

        function create_user() {

            let formData = new FormData();
            formData.append('first_name', document.getElementById("first_name").value);
            formData.append('last_name', document.getElementById("last_name").value);
            formData.append('otchestvo', document.getElementById("otchestvo").value);
            formData.append('username', document.getElementById("username").value);
            formData.append('password', document.getElementById("password").value);
            formData.append('level', document.getElementById("level").value);
            var url = $("#create_btn").data("url");

            $.ajax({
                    headers: { "X-CSRFToken": "{{csrf_token}}" },
                    url: url,
                    processData: false,
                    contentType: false,
                    method: 'POST',
                    data: formData,
                    success: function (data) {
                        alert('успех!');
                    },
                    error: function (data) {
                        alert('Ошибка');
                    }
                });
        }
    </script>

{% endblock %}

templates/create_group.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading text-center">
                    Добавить пользователя
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label for="group_name">Наименование группы</label>
                        <input id="group_name" class="form-control" type="text" value=""/>
                    </div>
                    <div class="form-group">
                        <label for="students">Список студентов</label>
                        <select multiple id="students" class="form-control">
                            {% for student in student_list %}
                                {% if not student.studentgroup_set.count %}
                                    <option value="{{ student.id }}">{{ student.first_name }} {{ student.last_name }} {{ student.otchestvo }} {{ student.id }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>

                    <button id="create_btn" class="btn btn-info" onclick="create_group()"
                            data-url="{% url 'api_v1:create_group' %}">Добавить
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script>

        function create_group() {

            let formData = new FormData();
            formData.append('group_name', document.getElementById("group_name").value);

            for (i = 0; i < $("#students").val().length; i++) {
                formData.append('students', $("#students").val()[i]);
            }
            var url = $("#create_btn").data("url");

            $.ajax({
                headers: {"X-CSRFToken": "{{csrf_token}}"},
                url: url,
                processData: false,
                contentType: false,
                method: 'POST',
                data: formData,
                success: function (data) {
                    alert('успех!');
                },
                error: function (data) {
                    alert('Ошибка');
                }
            });
        }
    </script>

{% endblock %}

templates/create_lesson_info.html
{% extends 'base.html' %}

{% block content %}
     <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading text-center">
                    Добавить Дисциплину
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label for="name">Наименование предмета</label>
                        <input id="name" class="form-control" type="text"/>
                    </div>
                    <div class="form-group">
                        <label for="type">Тип</label>
                        <select class="form-control" id="type">
                            {% for type in type_list %}
                                 <option value="{{ type.id }}">{{type.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="teacher">Преподаватель</label>
                        <select class="form-control" id="teacher">
                             {% for teacher in teacher_list %}
                                 <option value="{{ teacher.id }}">{{teacher.first_name}} {{ teacher.last_name }}  {{ teacher.otchestvo }}</option>
                            {% endfor %}

                        </select>
                    </div>
                    <button id="create_btn" class="btn btn-info" onclick="create_lesson_info()" data-url="{% url 'api_v1:create_lesson_info' %}">Добавить</button>
                </div>
            </div>
        </div>
    </div>

    <script>

        function create_lesson_info() {

            let formData = new FormData();
            formData.append('name', document.getElementById("name").value);
            formData.append('type', document.getElementById("type").value);
            formData.append('teacher', document.getElementById("teacher").value);

            var url = $("#create_btn").data("url");

            $.ajax({
                    headers: { "X-CSRFToken": "{{csrf_token}}" },
                    url: url,
                    processData: false,
                    contentType: false,
                    method: 'POST',
                    data: formData,
                    success: function (data) {
                        alert('успех!');
                    },
                    error: function (data) {
                        alert('Ошибка');
                    }
                });
        }
    </script>
{% endblock %}

templates/group_list.html
{% extends 'base.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="right-div">
                <a class="btn btn-success" href="{% url 'profile:group_create' %}"> <i class="fa fa-plus "></i>Добавить</a>
            </div>
        </div>
        <div class="col-md-12">
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    Дисчеплины
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="lesson_info_table">

                            <thead>

                            <tr>
                                <th class="text-center">№</th>
                                <th class="text-center">Группа</th>
                                <th class="text-center">Кол-во</th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for group in studentgroup_list %}
                                <tr class="odd gradeX">
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ group.group_name }}</td>
                                    <td>{{ group.students.count }}</td>

                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>
                    </div>

                </div>
            </div>
            <!--End Advanced Tables -->
        </div>
    </div>

{% endblock %}

templates/profiles.html
{% extends "base.html" %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="right-div">
                <a class="btn btn-success" href="{% url 'profile:create_user' %}"> <i
                        class="fa fa-plus "></i>Добавить</a>
            </div>
        </div>
        <div class="col-md-12">
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    Список пользователей
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="lesson_info_table">

                            <thead>

                            <tr>
                                <th class="text-center">№</th>
                                <th class="text-center">Логин</th>
                                <th class="text-center">ФИО</th>
                                <th class="text-center">Роль</th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for profile in profile_list %}
                                <tr class="odd gradeX">
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ profile.user.username }}</td>
                                    <td>{{ profile.last_name }} {{ profile.first_name }} {{ profile.otchestvo }}</td>
                                    <td>{{ profile.get_level_display }}</td>

                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>
                    </div>

                </div>
            </div>
            <!--End Advanced Tables -->
        </div>

    </div>




{% endblock %}